#!/usr/bin/env bash
###############################################################################
# AFT container entrypoint.
#
# 1. Initialise the Postgres data dir on first boot.
# 2. Start a temporary Postgres instance, create the AFT role/database, then
#    stop it. Subsequent boots skip this step.
# 3. Generate /etc/nginx/conf.d/proxy_secret.conf from $AFT_PROXY_SHARED_SECRET
#    so the nginx → bun shared-secret header matches what the app expects.
# 4. Hand off to supervisord to manage Postgres + nginx + Bun.
###############################################################################
set -euo pipefail

PGDATA="${PGDATA:-/var/lib/postgresql/data}"
POSTGRES_USER="${POSTGRES_USER:-aft}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-}"
POSTGRES_DB="${POSTGRES_DB:-aft}"

if [ -z "$POSTGRES_PASSWORD" ]; then
    echo "[entrypoint] ERROR: POSTGRES_PASSWORD must be set" >&2
    exit 1
fi

if [ -z "${AFT_PROXY_SHARED_SECRET:-}" ]; then
    echo "[entrypoint] ERROR: AFT_PROXY_SHARED_SECRET must be set" >&2
    exit 1
fi

# Export the DATABASE_URL the Bun app will read. Use the local unix socket so
# we don't need to encode credentials in the URL.
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:5432/${POSTGRES_DB}"

###############################################################################
# Step 1 + 2: bootstrap Postgres on first run
###############################################################################
if [ ! -s "$PGDATA/PG_VERSION" ]; then
    echo "[entrypoint] Initialising Postgres data dir at $PGDATA"
    mkdir -p "$PGDATA"
    chown postgres:postgres "$PGDATA"
    chmod 700 "$PGDATA"

    gosu postgres /usr/lib/postgresql/17/bin/initdb \
        -D "$PGDATA" \
        --encoding=UTF8 \
        --locale=C.UTF-8 \
        --auth-host=scram-sha-256 \
        --auth-local=trust \
        --username=postgres

    # Listen on localhost only - nothing outside the container should reach pg.
    cat >> "$PGDATA/postgresql.conf" <<EOF
listen_addresses = '127.0.0.1'
unix_socket_directories = '/var/run/postgresql,/tmp'
password_encryption = scram-sha-256
log_timezone = 'UTC'
timezone = 'UTC'
EOF

    cat > "$PGDATA/pg_hba.conf" <<EOF
# AFT default pg_hba.conf
local   all             postgres                                trust
local   all             all                                     scram-sha-256
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256
EOF

    echo "[entrypoint] Starting temporary Postgres to create role/database"
    gosu postgres /usr/lib/postgresql/17/bin/pg_ctl \
        -D "$PGDATA" -l /tmp/pg-bootstrap.log -w start

    gosu postgres psql -v ON_ERROR_STOP=1 --username postgres <<-SQL
        CREATE ROLE ${POSTGRES_USER} WITH LOGIN PASSWORD '${POSTGRES_PASSWORD}';
        ALTER ROLE ${POSTGRES_USER} CREATEDB;
        CREATE DATABASE ${POSTGRES_DB} OWNER ${POSTGRES_USER};
SQL

    gosu postgres /usr/lib/postgresql/17/bin/pg_ctl \
        -D "$PGDATA" -m fast -w stop

    echo "[entrypoint] Postgres bootstrap complete"
fi

###############################################################################
# Step 3: write the nginx → bun shared-secret include
###############################################################################
PROXY_SECRET_FILE=/etc/nginx/conf.d/proxy_secret.conf
mkdir -p /etc/nginx/conf.d
cat > "$PROXY_SECRET_FILE" <<EOF
# Auto-generated by aft-entrypoint.sh on container start.
# nginx forwards this header to the Bun process, which only accepts requests
# carrying the matching value (see index.ts).
proxy_set_header X-AFT-Proxy-Secret "${AFT_PROXY_SHARED_SECRET}";
EOF

###############################################################################
# Step 4: ensure nginx ssl directory + a self-signed fallback cert
###############################################################################
SSL_DIR=/etc/aft/ssl
mkdir -p "$SSL_DIR"
if [ ! -f "$SSL_DIR/cert.pem" ] || [ ! -f "$SSL_DIR/key.pem" ]; then
    echo "[entrypoint] Generating self-signed TLS certificate (development only)"
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout "$SSL_DIR/key.pem" \
        -out "$SSL_DIR/cert.pem" \
        -subj "/CN=aft.local/O=AFT/C=US" \
        > /dev/null 2>&1
    chmod 600 "$SSL_DIR/key.pem"
fi
# DOD CA bundle for client certificate verification (optional). When absent,
# nginx serves an empty file so the directive doesn't fail; client cert auth
# simply won't validate.
if [ ! -f "$SSL_DIR/dod-ca-bundle.pem" ]; then
    echo "" > "$SSL_DIR/dod-ca-bundle.pem"
fi

###############################################################################
# Step 5: hand off to supervisord
###############################################################################
exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
